service: nestjs-drizzle-aws-init

plugins:
  - serverless-localstack

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
  stage: ${opt:stage, 'local'}
  env: ${file(./env-${self:custom.stage}.yml)}

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: ${self:custom.stage}
  timeout: 30
  environment: ${self:custom.env.environment}
  ecr:
    images:
      nestjs-drizzle-aws-init:
        path: ./

functions:
  main:
    image:
      name: nestjs-drizzle-aws-init
      command: dist/src/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
